// Codex app-server protocol names TeamBot depends on.
// Verified against the schema generated from the pinned codex-cli version
// (see PINNED_CODEX_CLI_VERSION and src/codex/schema/, generated by
// `codex app-server generate-ts`). The test in tests/codex-protocol-names.test.ts
// asserts every name below still exists in the generated schema, so a codex
// upgrade that renames/removes a method fails CI instead of failing at runtime.

/** Client -> server request methods used by the Codex adapter. */
export const REQUIRED_CLIENT_METHODS = [
  "initialize",
  "thread/start",
  "thread/resume",
  "turn/start",
  "turn/steer",
  "turn/interrupt",
] as const;

/** Client -> server notifications used by the Codex adapter. */
export const REQUIRED_CLIENT_NOTIFICATIONS = ["initialized"] as const;

/** Server -> client events the adapter listens for to drive job state. */
export const REQUIRED_SERVER_EVENTS = [
  "thread/started",
  "turn/started",
  "turn/completed",
  "item/started",
  "item/completed",
] as const;

/** Server -> client approval/input requests the adapter must answer. */
export const REQUIRED_SERVER_REQUESTS = [
  "item/commandExecution/requestApproval",
  "item/fileChange/requestApproval",
  "item/permissions/requestApproval",
  "item/tool/requestUserInput",
] as const;

/** All protocol names TeamBot's design commits to. */
export const ALL_REQUIRED_PROTOCOL_NAMES = [
  ...REQUIRED_CLIENT_METHODS,
  ...REQUIRED_CLIENT_NOTIFICATIONS,
  ...REQUIRED_SERVER_EVENTS,
  ...REQUIRED_SERVER_REQUESTS,
] as const;
